# 🏋️‍♂️ Retos de Pandas - Ronda 2 (Nivel Avanzado)
¡Felicidades por superar la primera ronda! Ya dominas la limpieza básica. Ahora vamos a practicar habilidades más avanzadas que usarás muchísimo en la vida real para analizar datos.

**Regla principal:** ¡Recuerda siempre poner `df_retoX =` al principio para atrapar el resultado!

In [25]:
import pandas as pd

# Ejecuta esta celda para crear tu NUEVA base de datos de entrenamiento
datos = {
    'Nombre Completo': ['Carlos Perez', 'Ana Gomez', 'Luis Silva', 'Maria Paz', 'Juan Diaz'],
    'Clase': ['B1.1', 'B1.1', 'B1.2', 'B1.1', 'B1.2'],
    'Nota_Test_1': [80.0, 95.0, 60.0, 75.0, 40.0],
    'Nota_Test_2': [90.0, 95.0, 70.0, 85.0, 50.0]
}
df_practica = pd.DataFrame(datos)
df_practica

  Nombre Completo Clase  Nota_Test_1  Nota_Test_2
0    Carlos Perez  B1.1         80.0         90.0
1       Ana Gomez  B1.1         95.0         95.0
2      Luis Silva  B1.2         60.0         70.0
3       Maria Paz  B1.1         75.0         85.0
4       Juan Diaz  B1.2         40.0         50.0

## 🥊 Reto 1: El Arte de Renombrar
**Misión:** Las columnas tienen mayúsculas y espacios (ej. `'Nombre Completo'`), lo cual es un dolor de cabeza para programar en el futuro. Cambia el nombre de la columna `'Nombre Completo'` a `'estudiante'`, y `'Clase'` a `'clase'`.

💡 **Pistas:** 
- Usa el comando `.rename(columns={'Nombre Viejo': 'nombre_nuevo'})`.
- Puedes cambiar varias columnas al mismo tiempo separándolas con comas dentro de las llaves `{}`.
- ¡No olvides guardar el resultado sobrescribiendo la variable!

In [33]:
# Escribe tu código aquí para el Reto 1:
# ¡Atrapamos el resultado con df_reto1 = !
df_reto1 = df_practica.copy()
df_reto1 = df_reto1.rename(columns={'Nombre Completo' : 'estudiante','Clase':'clase'})
df_reto1

     estudiante clase  Nota_Test_1  Nota_Test_2
0  Carlos Perez  B1.1         80.0         90.0
1     Ana Gomez  B1.1         95.0         95.0
2    Luis Silva  B1.2         60.0         70.0
3     Maria Paz  B1.1         75.0         85.0
4     Juan Diaz  B1.2         40.0         50.0

## 🥊 Reto 2: Matemáticas de Pandas
**Misión:** Crea una **nueva columna** al final de la tabla llamada `'Promedio_Final'` que calcule automáticamente el promedio de las dos notas (`Nota_Test_1` y `Nota_Test_2`).

💡 **Pistas:** 
- Para crear una columna nueva, solo declárala: `df['Nueva Columna'] = ...`
- En Pandas, sumar dos columnas es tan fácil como sumar dos variables: `df['col1'] + df['col2']`.
- Para crear el promedio matemático, suma las dos columnas (¡usa paréntesis!) y divide el resultado entre 2.

In [36]:
# Escribe tu código aquí para el Reto 2:
df_reto2 = df_reto1.copy()

df_reto2['Promedio_Final'] = (df_reto2['Nota_Test_1'] + df_reto2['Nota_Test_2'])/2
df_reto2

     estudiante clase  Nota_Test_1  Nota_Test_2  Promedio_Final
0  Carlos Perez  B1.1         80.0         90.0            85.0
1     Ana Gomez  B1.1         95.0         95.0            95.0
2    Luis Silva  B1.2         60.0         70.0            65.0
3     Maria Paz  B1.1         75.0         85.0            80.0
4     Juan Diaz  B1.2         40.0         50.0            45.0

## 🥊 Reto 3: Filtrado de Doble Condición
**Misión:** El colegio quiere premiar a los mejores. Crea una tabla que contenga ÚNICAMENTE a los estudiantes que están en la clase `'B1.1'` **Y** que tienen un `'Promedio_Final'` mayor o igual a `85.0`.

💡 **Pistas:** 
- Para unir dos condiciones lógicas en Pandas, se usa el símbolo ampersand `&` (que significa AND).
- ¡Regla de oro! Debes poner CADA condición entre paréntesis o Pandas se confundirá.
- Estructura de ejemplo: `df = df[(condicion_1) & (condicion_2)]`.

In [44]:
from pandas.core.interchange import from_dataframe
# Escribe tu código aquí para el Reto 3:
# Fíjate cómo cada paréntesis envuelve una pregunta completa usando df_reto3[...]
#df_reto3 = df_reto3[(df_reto3['clase'] == 'B1.1') & (df_reto3['Promedio_Final'] >= 85.0)]
df_reto3 = df_reto2
df_reto3 = df_reto3[(df_reto3['clase']=='B1.1') & (df_reto3['Promedio_Final'] >= 85.0)]
df_reto3

     estudiante clase  Nota_Test_1  Nota_Test_2  Promedio_Final
0  Carlos Perez  B1.1         80.0         90.0            85.0
1     Ana Gomez  B1.1         95.0         95.0            95.0

## 🥊 Reto 4: Agrupando el Rebaño (Groupby)
**Misión:** Queremos saber **cuántos** estudiantes están matriculados en cada clase. Agrupa la tabla original por `'clase'` y cuenta cuántos estudiantes tiene cada una.

💡 **Pistas:** 
- Usa el poderoso comando `.groupby('columna')`. Esto crea grupos invisibles en la memoria.
- Después de agrupar, debes decirle a Pandas qué quieres hacer con esos grupos usando `.count()` (que significa contar cuántas filas hay).
- La estructura se encadena así: `df.groupby(...).count()`

In [49]:
# Escribe tu código aquí para el Reto 4 (Usa df_reto2 que tiene todos los estudiantes):
df_reto4 = df_reto2.copy()

df_reto4.groupby('clase').count()

       estudiante  Nota_Test_1  Nota_Test_2  Promedio_Final
clase
B1.1            3            3            3               3
B1.2            2            2            2               2